### Quiz

In [29]:
import numpy as np

##### 1. 5개의 1로 이루어진 정수데이터 타입의 벡터를 만드세요

In [ ]:
np.ones([5])

##### 2. 10개의 1로 이루어진 정수 데이터 타입의 벡터에서 마지막 3개의 데이터는 5가 들어있는 벡터를 만드세요

In [ ]:
arr1 = np.ones([5]).reshape(1,5)
arr2 = (np.ones([3]) * 5).reshape(1,3)
np.concatenate([arr1, arr2], axis = 1)

In [ ]:
data = np.ones(10, dtype= int)
data[-3 : ] = 5
data

##### 3. 10에서 20까지의 데이터를 가지는 벡터를 만드세요

In [ ]:
np.array(range(10, 20 + 1))

In [ ]:
np.arange(10, 20 + 1)

##### 4. 위 벡터의 순서를 바꾸세요

In [ ]:
np.array(range(20, 9, -1))

##### 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요

In [ ]:
arr = np.array(range(0, 8 +1)).reshape(3,3)
arr

##### 6. 위의 벡터에서  `[[4,5],[7,8]]`  행렬을 만드세요

In [ ]:
arr[1:, 1:]

##### 7. 1에서 10까지의 데이터를 랜덤하게 가지는 3*4 행렬을 만드세요

In [ ]:
arr = np.random.randint(10, size = (3,4))

##### 8. 위에서 만든 행렬의 unique 한 숫자들 리스트와 각숫자의 갯수를 리스트로 나타내세요

In [ ]:
index, count = np.unique(arr, return_counts = True)
index, count

##### 9. 1에서 12까지에 숫자가 들어간 3*4 행렬을 만드시고 행과 열에 관계없이 데이터를 섞으세요

In [ ]:
arr = np.random.randint(12, size = (3,4))

In [ ]:
np.random.shuffle(arr)
arr

##### 10. 1부터 10까지의 랜덤한 데이터가 들어가는 `3*3`행렬을 만드시고 가장 아래에 위의 데이터를 모두 합한 `1*3`행렬을 추가해서 `4*3`행렬을 만드세요

In [ ]:
import numpy as np
arr = np.random.randint(10, size = (3, 3))
arr

In [ ]:
# 선생님 답
sum_data = np.sum(arr, axis = 0).reshape(1,3)
np.concatenate( [arr, sum_data])

In [ ]:
r1, r2, r3 = np.hsplit(arr, [1,2])
last = np.array([sum(r1), sum(r2), sum(r3)]).reshape(1, 3)
answer = np.concatenate([arr, last], axis = 0)
answer

##### 11. 10번문제의 결과로 나온 행렬데이터에서 평균값을 출력하고 평균값보다 큰 숫자들만 유니크한 리스트로 나열하세요 (평균값은 소수 둘째 자리까지만 나타내세요)

In [ ]:
result = []
for i in answer :
    for j in i :
        result.append(j)
print("avg : ", round(sum(result)/len(result), 2))
np.unique(result)

##### 12. 1부터 20까지의 랜덤숫자를 가지는 5*5 행렬을 만드시고 최대값에는 숫자(MAX), 최소값에는 숫자(MIN)으로 행렬을 바꾸세요

In [2]:
import numpy as np
array = np.random.randint(20,  size = (5, 5))
array

array([[ 3,  8, 14, 11,  3],
       [ 0, 19,  4,  0, 10],
       [17, 16,  3, 16,  8],
       [ 6, 18,  3, 17, 15],
       [13,  5, 11,  2, 12]])

In [3]:
import numpy as np
min_number = array.min()
max_number = array.max()
min_idx = array == min_number
max_idx = array == max_number


In [4]:
array = array.astype("str")
array[max_idx] = str(max_number) + "(MAX)"
array[min_idx] = str(min_number) + "(MIN)"
array

array([['3', '8', '14', '11', '3'],
       ['0(MIN)', '19(MAX)', '4', '0(MIN)', '10'],
       ['17', '16', '3', '16', '8'],
       ['6', '18', '3', '17', '15'],
       ['13', '5', '11', '2', '12']],
      dtype='<U21')

#### 13. 100에서 130까지의 랜덤 숫자를 가지는 8*8행렬을 만드시고 3의 배수에는 fiz, 5의 배수에는 buz, 3과 5의 배수는 fbz 문자를 출력하세요

In [24]:
data = np.random.randint(100, 130 + 1, size = (8, 8))
data

array([[103, 126, 127, 127, 129, 121, 108, 103],
       [107, 116, 110, 118, 123, 110, 102, 120],
       [115, 116, 122, 128, 119, 105, 121, 120],
       [107, 110, 114, 127, 101, 112, 100, 117],
       [117, 124, 107, 110, 103, 121, 108, 111],
       [105, 127, 103, 115, 117, 110, 129, 114],
       [124, 102, 109, 120, 118, 115, 130, 117],
       [123, 125, 110, 108, 110, 102, 127, 120]])

In [25]:
data

array([[103, 126, 127, 127, 129, 121, 108, 103],
       [107, 116, 110, 118, 123, 110, 102, 120],
       [115, 116, 122, 128, 119, 105, 121, 120],
       [107, 110, 114, 127, 101, 112, 100, 117],
       [117, 124, 107, 110, 103, 121, 108, 111],
       [105, 127, 103, 115, 117, 110, 129, 114],
       [124, 102, 109, 120, 118, 115, 130, 117],
       [123, 125, 110, 108, 110, 102, 127, 120]])

In [26]:
fifteen = data % 15 == 0

In [27]:
data = data.astype("str")
data[three] = "fiz"
data[five] = "buz"
data[fifteen] = "fbz"

In [28]:
data

array([['103', 'buz', '127', 'fiz', '129', '121', '108', '103'],
       ['fiz', '116', 'fiz', 'fiz', '123', 'fiz', '102', 'fbz'],
       ['115', '116', 'fiz', 'fiz', 'buz', 'fbz', '121', 'fbz'],
       ['107', 'buz', '114', 'buz', '101', 'buz', 'buz', '117'],
       ['117', 'buz', '107', 'fiz', '103', '121', 'fiz', 'fiz'],
       ['fbz', 'fiz', '103', '115', '117', 'buz', '129', '114'],
       ['124', '102', '109', 'fbz', 'buz', '115', 'fiz', 'buz'],
       ['buz', '125', 'buz', 'fiz', '110', '102', '127', 'fbz']],
      dtype='<U21')

In [ ]:
import numpy as np
data =np.random.randint(100, 131, size = (8, 8))
data

In [ ]:
idx_3 = data % 3 == 0
idx_5 = data % 5 == 0
idx_15 = data % 15 == 0

In [ ]:
data = data.astype("str")
data[idx_3] = "fiz"
data[idx_5] = "buz"
data[idx_15] = "fbz"
data

##### 14. 리스트 컴프리헨션을 이용하여 아래와 같은 규칙은 갖는 행렬을 만드세요

In [36]:
n = int(input("number : "))
result = np.array([[ i * j for j in range(1, n + 1)] for i in range(1, n + 1)])
result

number : 7


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 2,  4,  6,  8, 10, 12, 14],
       [ 3,  6,  9, 12, 15, 18, 21],
       [ 4,  8, 12, 16, 20, 24, 28],
       [ 5, 10, 15, 20, 25, 30, 35],
       [ 6, 12, 18, 24, 30, 36, 42],
       [ 7, 14, 21, 28, 35, 42, 49]])