### Datatype
- boolean : bool
- integer : int64 (64는 byte를 의미함)
- float : float64
- byte String : S24
- unicode String : U24

In [2]:
import numpy as np

In [5]:
na = np.array([True, False])
na.dtype

dtype('bool')

In [13]:
na = np.array([1, 2, 3])
na.dtype

dtype('int32')

In [7]:
na = np.array([1.0, 2.0, 3.0])
na.dtype

dtype('float64')

##### change datatype

In [14]:
na = np.array([-1.0, 0.0, 1.0, 2.2, 3.8])
print(na)

na = na.astype('int64')
print(na)

na = na.astype('bool')
print(na)

na = na.astype('S24')
print(na)

na = na.astype('U24')
print(na)

[-1.   0.   1.   2.2  3.8]
[-1  0  1  2  3]
[ True False  True  True  True]
[b'True' b'False' b'True' b'True' b'True']
['True' 'False' 'True' 'True' 'True']


In [9]:
# 5~10까지 랜덤한 숫자가 들어있는 5*5 행렬
na = np.random.rand(3, 3)
print(na)

na = (na*3+5).astype('int64')
print(na)

[[0.88670127 0.67471656 0.1468773 ]
 [0.63883273 0.46239334 0.91771898]
 [0.71393252 0.70861838 0.73504682]]
[[7 7 5]
 [6 6 7]
 [7 7 7]]
