### Calculate
- basic calculate
- broadcasting # 행렬 데이터로 전부 쓸 필요 없이, 하나의 숫자로 전체 데이터로 곱해지는 개념.
- functions    
- performance

In [1]:
import numpy as np

##### basic calculate

In [ ]:
# list ( ls *= 3 )
ls = [1,2,3,4,5]
print("before : {}".format(ls))
for idx in range(len(ls)):
    ls[idx] = ls[idx] * 3
print("after : {}".format(ls))

In [ ]:
# np.array ( na *= 3 )
na = np.array(ls)
na *= 3
print(type(na), na)

In [ ]:
na_2 = np.array([6,7,8,9,10])
result = na * na_2
print("{}\n{}\n{}".format(na, na_2, result))

In [ ]:
# 9와 같으면 True, 30보다 크면 True
na == 9, na > 30

In [ ]:
# 3의 배수이면 True
idx = na_2 % 3 == 0
print(idx)

In [ ]:
# 3의 배수만 남기기 - Ture, False 리스트를 offset으로 넣어주면 True인 데이터만 남는다.
print(na_2)
print(na_2[idx])

In [ ]:
# 리스트에서 같은 수 추출하기 / function filter와 유사한 역할
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 == na2)
print(na1[na1 == na2])

In [ ]:
# 리스트에서 비교연산으로 수 추출하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
print(na1 >= na2)
print(na1[na1 >= na2])

In [ ]:
# 전체 리스트 비교하기
na1 = np.array([1,2,3,4,5])
na2 = np.array([1,3,3,4,4])
na3 = np.array([1,2,3,4,5])
print(np.all(na1 == na2))
print(np.all(na1 == na3))

In [ ]:
# 스칼라, 벡터, 행렬 각 요소 곱셈
na = np.arange(6)
na2 = np.arange(6,12)

print("array1 : {}".format(na))
print("array2 : {}".format(na2))

print("scala : {}".format(na * 10))
print("vector : {}".format(na * na2))

na3 = na.reshape(2,3)
na4 = na2.reshape(2,3)
print("array3 : \n{}".format(na3))
print("array4 : \n{}".format(na4))
print("matrix : \n{}".format(na3 * na4))

##### broadcasting 하나의 데이터를 곱했을 때 모든 요소에 곱해지는 것을 일컫음

In [ ]:
# broadcating exam 1  
na1 = np.arange(12)
na2 = na1.reshape(3,4)
print("na1 : \n{}".format(na1))
print("na2 : \n{}".format(na2))

na3 = np.ones_like(na1)
na3 = na3.reshape(3,4)
print("na3 : \n{}".format(na3))

print("na2 + 1 : \n{}".format(na2 + 1)) # + 1 만해도 행렬의 모든 요소에 1을 다 더한다. (broadcating 개념)
print("na2 + na3 : \n{}".format(na2 + na3))

In [ ]:
# broadcating exam 2
na4 = np.arange(4)
print("na2 : \n{}".format(na2))
print("na4 : \n{}".format(na4))

print("na2 + na4 : \n{}".format(na2 + na4)) # 모든 행에 n4를 다 더한다.

na5 = np.stack((na4, na4, na4))
print("na5 : \n{}".format(na5))

print("na2 + na5 : \n{}".format(na2 + na5))

In [ ]:
# broadcating exam 3

na6 = np.arange(3)[:,np.newaxis]
print("na2 : \n{}".format(na2))
print("na6 : \n{}".format(na6))

print("na2 + na6 : \n{}".format(na2 + na6)) # 모든 열에 na6를 다 더한다.

na7 = np.array([[ i for _ in range(4)] for i in range(3)])
print("na7 : \n{}".format(na7))

print("na2 + na7 : \n{}".format(na2 + na7))

##### functions
- min, max, argmin, argmax
- sum, mean, median, std, var
- all, any
- quartile
- exp, log

In [2]:
import numpy as np
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("min : {}".format(r_num.min()))
print("max : {}".format(r_num.max()))
print("argmin : {}".format(r_num.argmin())) # 최소값 위치
print("argmax : {}".format(r_num.argmax())) # 최대값 위치
print("mean : {}".format(r_num.mean()))

random matrix : 
[[4 9 3]
 [3 2 8]]
min : 2
max : 9
argmin : 4
argmax : 1
mean : 4.833333333333333


In [ ]:
r = np.random.rand(2,3)
r_num = np.arange(5)
r_num = (r*10).astype('int64')
print("random matrix : \n{}".format(r_num))
print("sum : {}".format(np.sum(r_num)))
print("sum_axis_0 : {}".format(np.sum(r_num, axis=0)))
print("sum_axis_1 : {}".format(np.sum(r_num, axis=1)))
print("median : {}".format(np.median(r_num)))
print("std : {}".format(np.std(r_num))) # standard deviation (표준편차)
print("var : {}".format(np.var(r_num))) # variance (변화량)

In [2]:
# all
# 모든 요소의 조건이 충족하면 True
n1 = np.array(range(3,8))
n2 = n1
n3 = np.array(range(1,11,2))

print(n1, n2, n3, end="\n\n")

print(n1 ==  n2)
print(np.all(n1 ==  n2)) # any와 all을 이용. ndarray 데이터 비교
print(n1 ==  n3)
print(np.all(n1 ==  n3))
print(n1 >  n3)
print(np.all(n1 >  n3))

[3 4 5 6 7] [3 4 5 6 7] [1 3 5 7 9]

[ True  True  True  True  True]
True
[False False  True False False]
False
[ True  True False False False]
False


In [ ]:
# any
# 요소의 하나라도 조건이 충족하면 True
n1 = np.array(range(3,8))
n2 = n1
n3 = np.array(range(1,11,2))

print(n1, n2, n3, end="\n\n")

print(n1 ==  n2)
print(np.any(n1 ==  n2))
print(n1 ==  n3)
print(np.any(n1 ==  n3))
print(n1 >  n3)
print(np.any(n1 >  n3))

In [ ]:
# quartile (사분위수)
na = np.array([num for num in range(50,100 + 1)])
print(na)
np.percentile(na, 25), np.percentile(na, 45)  

In [ ]:
# exponential function (지수함수) # 데이터가 너무 작아, 확대해서 보고 싶을 때
na = np.arange(1,11)
print(na)
print(np.exp(na))

In [ ]:
# log function (로그함수) # 데이터가 너무 커서 작게 해서 보고 싶을때
na = np.arange(1,6)
print(na)
print(np.log(na))

##### performance
- 10**7개의 리스트에서 3과 5의 배수의 갯수를 찾는 시간

In [ ]:
ls = []
size = int(1E7)
for data in range(size):
    ls.append(data)
na = np.array(ls)

In [ ]:
%%time
count = 0
for idx in range(len(ls)):
    if (ls[idx] % 3 == 0) or (ls[idx] % 5 == 0):
        count += 1
print(count)

In [ ]:
%%time
count = len(na[(na%3 == 0) | (na%5 == 0)])
print(count)